import type { Heading, PhrasingContent, Root } from "mdast";
import { marked } from "marked";
import remarkParse from "remark-parse";
import { unified } from "unified";

/**
 * Converts a single line / inline markdown fragment to HTML. Used by the render
 * components to turn the inline text state (bold, italic, links, code) into HTML.
 */
export function markdownToHtml(markdown: string): string {
  return marked.parseInline(markdown) as string;
}

/**
 * Builds a stable anchor id from a heading title, matching the ids generated by
 * the heading render components so table-of-contents links resolve correctly.
 */
export function createMarkdownHeadingId(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^\w\s-]/g, "")
    .replace(/\s+/g, "-")
    .trim();
}

export interface MarkdownHeading {
  id: string;
  title: string;
}

/**
 * Parses a markdown string and returns the plain-text + anchor id of every heading
 * at the given depth. The ids use the same slugify as the heading render components,
 * so table-of-contents links resolve to the rendered anchors.
 */
export function extractMarkdownHeadings(markdown: string, depth = 2): MarkdownHeading[] {
  const tree = unified().use(remarkParse).parse(markdown) as Root;
  const headings: MarkdownHeading[] = [];

  for (const node of tree.children) {
    if (node.type !== "heading") continue;
    const heading = node as Heading;
    if (heading.depth !== depth) continue;

    const title = heading.children.map(phrasingToPlainText).join("").trim();
    if (title) {
      headings.push({ id: createMarkdownHeadingId(title), title });
    }
  }

  return headings;
}

function phrasingToPlainText(content: PhrasingContent): string {
  if (content.type === "text" || content.type === "inlineCode") {
    return content.value;
  }
  if ("children" in content && Array.isArray(content.children)) {
    return content.children.map(phrasingToPlainText).join("");
  }
  return "";
}
